server:
  port: 8082
  servlet:
    context-path: /notification

spring:
  application:
    name: notification-service
  data:
    mongodb:
      #uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASS:root}@${MONGO_HOST:mongodb-container}:${MONGO_PORT:27017}/notification-service?authSource=admin

  kafka:
    bootstrap-servers: ${KAFKA_HOSTNAME:localhost}:${KAFKA_PORT:9094}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apiKey: ${BREVO_API_KEY:xkeys}