server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    #url: "jdbc:mysql://localhost:3306/identity_service"
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:642004}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    #bootstrap-servers: localhost:9094
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

#app:
#  services:
#    profile: http://localhost:8081/profile

app:
  services:
    profile: http://${PROFILE_HOST:profile-service}:${PROFILE_PORT:8081}/profile

