server:
  port: 8888

app:
  api-prefix: /api/v1
  base-url: ${BASE_URL:http://localhost:8080/identity}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          #uri: http://localhost:8080
          uri: http://${IDENTITY_SERVICE_HOST:localhost}:${IDENTITY_SERVICE_PORT:8080}
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-service
          #uri: http://localhost:8081
          uri: http://${PROFILE_SERVICE_HOST:localhost}:${PROFILE_SERVICE_PORT:8081}
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2
        - id: notification-service
          #uri: http://localhost:8082
          uri: http://${NOTIFICATION_SERVICE_HOST:localhost}:${NOTIFICATION_SERVICE_PORT:8082}
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: post-service
          #uri: http://localhost:8083
          uri: http://${POST_SERVICE_HOST:localhost}:${POST_SERVICE_PORT:8083}
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: file-service
          #uri: http://localhost:8084
          uri: http://${FILE_SERVICE_HOST:localhost}:${FILE_SERVICE_PORT:8084}
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=2



