server:
  port: 8084
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      #uri: mongodb://root:root@localhost:27017/file-service?authSource=admin
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASS:root}@${MONGO_HOST:mongodb-container}:${MONGO_PORT:27017}/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


app:
  file:
    storage-dir: ${STORAGE_DIR:D:/file-service-upload}
    download-prefix: http://localhost:8888/api/v1/file/media/download/