server:
  port: 8081
  servlet:
    context-path: /profile


spring:
  neo4j:
    uri: bolt://${NEO4J_HOST:localhost}:${NEO4J_PORT:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


app:
  services:
    #file: http://localhost:8084
    file: http://${FILE_SERVICE_HOST:localhost}:${FILE_SERVICE_PORT:8084}

